export const SET_DONOR = 'SET_DONOR';
export const CLEAR_DONOR = 'CLEAR_DONOR';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';

export const SET_CURRENT_CHARITIES = 'SET_CURRENT_CHARITIES';
export const APPEND_CURRENT_CHARITIES = 'APPEND_CURRENT_CHARITIES';

export const SET_BASKET_ITEMS = 'SET_BASKET_ITEMS';
export const CLEAR_BASKET_ITEMS = 'CLEAR_BASKET_ITEMS';

export const SET_COMPLETED_BASKET_ITEMS = 'SET_COMPLETED_BASKET_ITEMS';

export const SET_TOP_CHARITIES = 'SET_TOP_CHARITIES';

export const SET_GIVING_HISTORY = 'SET_GIVING_HISTORY';

