export const types = {

  FETCH_KEYWORDS: 'FETCH_KEYWORDS',
  FETCH_KEYWORDS_SUCCESS: 'FETCH_KEYWORDS_SUCCESS',

  FETCH_CAMPAIGNS: 'FETCH_CAMPAIGNS',
  FETCH_CAMPAIGNS_SUCCESS: 'FETCH_CAMPAIGNS_SUCCESS',

  FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS',
  FETCH_NOTIFICATIONS_SUCCESS: 'FETCH_NOTIFICATIONS_SUCCESS',
};
