export const types = {
  SET_KEYWORD_COUNT: 'SET_KEYWORD_COUNT',
  SET_KEYWORDS: 'SET_KEYWORDS',

  SET_CAMPAIGN_COUNT: 'SET_CAMPAIGN_COUNT',
  SET_CAMPAIGNS: 'SET_CAMPAIGNS',

  SET_NOTIFICATION_COUNT: 'SET_NOTIFICATION_COUNT',
  SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
};
